version: '3'
services:
  api:
    container_name: 'api_lista'
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    container_name: 'db_lista'
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  # pgadmin:
  #   container_name: 'pgadmin_lista'
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     - db
volumes:
  db-data:
